# https://stackoverflow.com/questions/51809421/flutter-is-not-able-to-install-the-apk-into-the-real-device-suddenly
# flutter build apk --obfuscate --split-debug-info=Sway/debug_info

name: sway
description: Sway is a mobile event management application that helps users discover, organize, and manage events effortlessly. Sway aims to provide a seamless and intuitive experience for both event attendees and promoters.

publish_to: "none"

version: 0.2.4 # Database migration #3 - Refactor artist data retrieval to use Supabase instead of local JSON storage


environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  bloc: ^8.1.4
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.0.2
  root_jailbreak_sniffer: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_sticky_header: ^0.6.5
  go_router: ^14.2.1 # ^6.5.9 important
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  # isar: ^3.1.0+1 # Super Fast Cross-Platform Database - For bigger projects with more complex data structures - https://isar.dev/ - https://pub.dev/packages/isar
  lemon_squeezy: ^1.0.3
  # onesignal_flutter: ^5.2.2
  qr_flutter: ^4.1.0
  responsive_framework: ^1.4.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.11
  uuid: ^4.4.2

dev_dependencies:
  firebase_crashlytics: ^4.0.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  plausible_analytics: ^0.3.0

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/icon.png"
#   web:
#     generate: true
#     image_path: "assets/images/icon.png"
#     background_color: "#800020"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/images/icon.png"
#   macos:
#     generate: true
#     image_path: "assets/images/icon.png"

flutter_launcher_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: "launcher_icon"
  ios: true
  adaptative_icon_background: "#assets/images/icon_background.png"
  adaptative_icon_foreground: "assets/images/icon.png"
  adaptative_icon_monochrome: "assets/images/icon_monochrome.png"
  min_sdk_version: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#FEBF1E"
  web:
    generate: false
    image_path: "assets/images/icon.png"
    background_color: "#FEBF1E"
    theme_color: "#FEBF1E"
  windows:
    generate: false
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/icon.png
    - assets/databases/events.json
    - assets/databases/artists.json
    - assets/databases/promoters.json
    - assets/databases/venues.json
    - assets/databases/genres.json
    - assets/databases/users.json
    - assets/databases/tickets.json
    - assets/databases/orders.json
    - assets/databases/invoices.json
    - assets/databases/items.json
    - assets/databases/join_table/user_permissions.json
    - assets/databases/join_table/artist_genre.json
    - assets/databases/join_table/event_artist.json
    - assets/databases/join_table/event_genre.json
    - assets/databases/join_table/event_promoter.json
    - assets/databases/join_table/similar_artists.json
    - assets/databases/join_table/venue_genres.json
    - assets/databases/join_table/venue_promoter.json
    - assets/databases/join_table/venue_resident_artists.json
    - assets/databases/join_table/user_follow_artist.json
    - assets/databases/join_table/user_follow_genre.json
    - assets/databases/join_table/user_follow_venue.json
    - assets/databases/join_table/user_follow_promoter.json
    - assets/databases/join_table/user_follow_user.json
    - assets/databases/join_table/user_interest_event.json
    - assets/databases/join_table/user_event_ticket.json
    - assets/databases/join_table/order_items.json

  generate: true
