name: sway_events
description: Sway Events is a multi-platform event management application that helps users discover, organize, and manage events effortlessly. Sway Events aims to provide a seamless and intuitive experience for both event attendees and organizers.

publish_to: "none"

version: 0.0.8 # Accessibility v1

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_shake_animated: ^0.0.5
  go_router: ^14.2.1 # ^6.5.9
  google_fonts: ^6.2.1
  intl: ^0.19.0
  responsive_framework: ^1.4.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0

dev_dependencies:
  # analyzer: ^6.7.0 # ^6.4.1
  firebase_crashlytics: ^4.0.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  lint: ^2.3.0
  plausible_analytics: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#800020"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/databases/events.json
    - assets/databases/artists.json
    - assets/databases/organizers.json
    - assets/databases/venues.json
    - assets/databases/genres.json
    - assets/databases/users.json
    - assets/databases/join_table/user_permissions.json
    - assets/databases/join_table/artist_genre.json
    - assets/databases/join_table/event_artist.json
    - assets/databases/join_table/event_genre.json
    - assets/databases/join_table/event_organizer.json
    - assets/databases/join_table/similar_artists.json
    - assets/databases/join_table/venue_genres.json
    - assets/databases/join_table/venue_organizers.json
    - assets/databases/join_table/venue_resident_artists.json
    - assets/databases/join_table/user_follow_artist.json
    - assets/databases/join_table/user_follow_genre.json
    - assets/databases/join_table/user_follow_venue.json
    - assets/databases/join_table/user_follow_organizer.json
    - assets/databases/join_table/user_follow_user.json
    - assets/databases/join_table/user_interest_event.json

  generate: true
