# https://stackoverflow.com/questions/51809421/flutter-is-not-able-to-install-the-apk-into-the-real-device-suddenly
# dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs
# flutter build apk --obfuscate --split-debug-info=Sway/debug_info
# flutter pub deps > deps.txt

name: sway
description: Sway is a mobile event management application that helps users discover, organize, and manage events effortlessly. Sway aims to provide a seamless and intuitive experience for both event attendees and promoters.

publish_to: "none"

version: 0.9.4 # Refactor and improve styling for the entities management screen

environment:
  sdk: ">=3.0.0 <4.0.0" # ">=2.18.5 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  bloc: ^9.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.0.2
  root_jailbreak_sniffer: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_sticky_header: ^0.7.0
  go_router: ^14.2.1 # ^6.5.9 was important before, keep it in ming
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  # lemon_squeezy: ^1.0.3
  # qr_flutter: ^4.1.0
  responsive_framework: ^1.4.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.11
  uuid: ^4.5.1
  file_picker: ^9.0.0
  flutter_pdfview: ^1.3.4
  screen_brightness: ^2.0.0+2
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^28.1.35
  syncfusion_flutter_pdf: ^28.1.35
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  expandable_text: ^2.3.0
  provider: ^6.1.2
  hcaptcha: ^0.0.2
  supabase_auth_ui: ^0.5.4
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  flutter_local_notifications: ^18.0.1
  in_app_purchase: ^3.2.0
  infinite_scroll_pagination: ^4.1.0
  timeago: ^3.7.0
  connectivity_plus: ^6.1.1
  shimmer: ^3.0.0
  app_links: ^6.3.3
  image_picker: ^1.1.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  maps_launcher: ^3.0.0+1
  flutter_typeahead: ^5.2.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  package_info_plus: ^8.2.1
  in_app_review: ^2.0.10
  flutter_markdown: ^0.7.6+2
  add_2_calendar: ^3.0.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  analyzer: any # ^5.13.0
  isar: ^3.1.0+1 # Super Fast Cross-Platform Database - For bigger projects with more complex data structures - https://isar.dev/ - https://pub.dev/packages/isar
  #isar: # Super Fast Cross-Platform Database - For bigger projects with more complex data structures - https://isar.dev/ - https://pub.dev/packages/isar
  #  hosted: https://pub.isar-community.dev
  #  version: 4.0.3
  isar_flutter_libs: ^3.1.0+1
  internet_connection_checker: ^3.0.1
  #isar_flutter_libs:
  #  hosted: https://pub.isar-community.dev
  #  version: 4.0.3

dev_dependencies:
  build_runner: any # ^2.4.13 no ^ to test?
  isar_generator: ^3.1.0+1 # any
  #git:
  #  url: https://github.com/isar-community/isar.git
  #  ref: 3.1.0+1
  #  path: packages/isar_generator
  firebase_crashlytics: ^4.0.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  # plausible_analytics: ^0.3.0

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/icon.png"
#   web:
#     generate: true
#     image_path: "assets/images/icon.png"
#     background_color: "#800020"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/images/icon.png"
#   macos:
#     generate: true
#     image_path: "assets/images/icon.png"

flutter_launcher_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: "launcher_icon"
  ios: true
  adaptative_icon_background: "#assets/images/icon_background.png"
  adaptative_icon_foreground: "assets/images/icon.png"
  adaptative_icon_monochrome: "assets/images/icon_monochrome.png"
  min_sdk_version: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#FEBF1E"
  web:
    generate: false
    image_path: "assets/images/icon.png"
    background_color: "#FEBF1E"
    theme_color: "#FEBF1E"
  windows:
    generate: false
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/icon.png
    - assets/images/logotype_transparent.png
    - assets/images/404.png
    - assets/data/forbidden_words_en.json
    - assets/data/forbidden_words_fr.json

  generate: true
