// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHoIKXnZxZyRQMm-2mdRYJxg1a6qAxR0E',
    appId: '1:757784524747:web:9b201e2f1df8587ee0a84e',
    messagingSenderId: '757784524747',
    projectId: 'sway-app-247f6',
    authDomain: 'sway-app-247f6.firebaseapp.com',
    storageBucket: 'sway-app-247f6.firebasestorage.app',
    measurementId: 'G-01M04SPJQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvA75qwZsIJVD66fu2Fo2bEdAbkYXhEE',
    appId: '1:757784524747:android:809e5ce5eb851c35e0a84e',
    messagingSenderId: '757784524747',
    projectId: 'sway-app-247f6',
    storageBucket: 'sway-app-247f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsT-q5xBEF_aZgYsESaeoCR6Iev9rDkD4',
    appId: '1:757784524747:ios:17681eebeb3eea0de0a84e',
    messagingSenderId: '757784524747',
    projectId: 'sway-app-247f6',
    storageBucket: 'sway-app-247f6.firebasestorage.app',
    iosBundleId: 'app.sway.main',
  );
}
