name: Runner
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '11.0'
targets:
  Runner:
    type: application
    platform: iOS
    sources: [Runner]
    dependencies:
      - target: OneSignalNotificationServiceExtension
  OneSignalNotificationServiceExtension:
    type: app-extension
    platform: iOS
    sources: [OneSignalNotificationServiceExtension]
    dependencies:
      - framework: OneSignalXCFramework