// https://codewithandrea.com/articles/flutter-localization-build-context-extension/
// flutter gen-l10n

import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:shared_preferences/shared_preferences.dart';

extension LocalizedBuildContext on BuildContext {
  AppLocalizations get loc => AppLocalizations.of(this); // AppLocalizations is generated by flutter_gen
}

class LanguageCubit extends Cubit<Locale> {
  LanguageCubit() : super(const Locale('en', '')) {
    chargeStartLang();
  }

  Future<void> chargeStartLang() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    final String? langCode = prefs.getString('lang');
    debugPrint(langCode);
    if (langCode != null) {
      emit(Locale(langCode, ''));
    }
  }

  Future<void> changeLang(BuildContext context, String data) async {
    emit(Locale(data, ''));
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString('lang', data);
  }
}
