name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Create Xcode project
      run: |
        mkdir -p ios
        cd ios
        xcodebuild -create-xcodeproj -project Runner.xcodeproj

    - name: Install dependencies
      run: pod install --project-directory=ios

    - name: Build iOS app
      run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' build