# .github/workflows/cleanup_anonymous_users.yml

name: Cleanup Anonymous Users

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Execute Cleanup SQL
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          PGPASSWORD=$SUPABASE_DB_PASSWORD psql $SUPABASE_DB_URL -c "
          DELETE FROM auth.users
          WHERE is_anonymous = true AND created_at < now() - interval '30 days';
          "
